"use client";

import { useState, useCallback } from 'react';
import { BrainCircuit, UploadCloud, CheckCircle2, Image as ImageIcon } from 'lucide-react';
import clsx from 'clsx';

export default function AIDetectPage() {
  const [file, setFile] = useState<File | null>(null);
  const [isScanning, setIsScanning] = useState(false);
  const [isDragging, setIsDragging] = useState(false);
  const [results, setResults] = useState<{ ai: number; real: number } | null>(null);

  const runScan = async (selectedFile: File) => {
    setFile(selectedFile);
    setIsScanning(true);
    setResults(null);

    try {
      const formData = new FormData();
      formData.append("file", selectedFile);

      const res = await fetch('http://localhost:8000/api/ai-detect', {
        method: 'POST',
        body: formData,
      });

      if (!res.ok) throw new Error("Engine unreachable");
      const data = await res.json();
      
      // Slight delay for UI smoothing
      setTimeout(() => {
        setResults(data.results);
        setIsScanning(false);
      }, 1000);

    } catch (error) {
      console.error(error);
      alert("Failed to run AI detection. Is Python running?");
      setIsScanning(false);
    }
  };

  const onDrop = useCallback((e: React.DragEvent<HTMLDivElement>) => {
    e.preventDefault();
    setIsDragging(false);
    if (e.dataTransfer.files && e.dataTransfer.files.length > 0) {
      runScan(e.dataTransfer.files[0]);
    }
  }, []);

  return (
    <div className="max-w-6xl mx-auto space-y-8 animate-in fade-in duration-500 pb-20">
      
      {/* Header */}
      <div className="border-b border-white/40 pb-6 flex flex-col md:flex-row md:items-center justify-between">
        <div>
          <h1 className="text-4xl font-black text-[#3E3B52] flex items-center tracking-tight">
            <div className="bg-emerald-500 p-2 rounded-2xl mr-4 shadow-lg shadow-emerald-200">
              <BrainCircuit className="w-8 h-8 text-white" />
            </div>
            AI Content Detection
          </h1>
          <p className="text-[#8E8AAB] mt-3 text-lg font-medium">
            Identify if an image was generated by AI (Midjourney, DALL-E, Stable Diffusion) using Swin Transformer models.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
        
        {/* Upload Column (Left) */}
        <div className="bg-white/60 backdrop-blur-xl border border-white p-8 rounded-[3rem] shadow-xl shadow-indigo-50/50 flex flex-col h-fit">
          <h2 className="text-xl font-black text-[#3E3B52] mb-6">Input Media</h2>
          
          {!file ? (
            <div
              onDragOver={(e) => { e.preventDefault(); setIsDragging(true); }}
              onDragLeave={() => setIsDragging(false)}
              onDrop={onDrop}
              className={clsx(
                "border-2 border-dashed rounded-[2rem] p-12 text-center transition-all flex flex-col items-center justify-center bg-white/40",
                isDragging ? "border-emerald-400 bg-emerald-50" : "border-[#A09CB0]/30 hover:border-emerald-400/50 cursor-pointer"
              )}
            >
              <input 
                type="file" accept="image/*" className="absolute inset-0 w-full h-full opacity-0 cursor-pointer hidden" id="ai-upload" 
                onChange={(e) => e.target.files && runScan(e.target.files[0])}
              />
              <div className="bg-white p-3 rounded-full shadow-sm mb-4">
                <UploadCloud className="w-8 h-8 text-emerald-500" />
              </div>
              <p className="text-[#3E3B52] font-black tracking-tight text-lg mb-1">Drag & drop suspect media</p>
              <p className="text-xs text-[#A09CB0] font-medium mb-6">JPG, PNG, WEBP</p>
              <label htmlFor="ai-upload" className="inline-block bg-[#3E3B52] text-white px-6 py-3 rounded-full text-xs font-black uppercase tracking-widest hover:bg-emerald-500 hover:scale-105 hover:shadow-lg hover:shadow-emerald-200 cursor-pointer transition-all relative z-10">
                Browse Files
              </label>
            </div>
          ) : (
            <div className="space-y-6">
              <div className="bg-white/80 p-4 rounded-[1.5rem] flex items-center border border-white shadow-sm">
                <div className="bg-emerald-100 p-3 rounded-xl mr-4">
                  <ImageIcon className="w-6 h-6 text-emerald-500" />
                </div>
                <div className="overflow-hidden">
                  <p className="text-sm font-black text-[#3E3B52] truncate">{file.name}</p>
                  <p className="text-xs text-[#8E8AAB] font-medium mt-1">{(file.size / 1024 / 1024).toFixed(2)} MB</p>
                </div>
              </div>
              <button 
                onClick={() => { setFile(null); setResults(null); }} 
                className="w-full text-[10px] font-black uppercase tracking-[0.2em] text-[#8E8AAB] hover:text-rose-500 transition-colors"
              >
                Clear & Scan Another
              </button>
            </div>
          )}
        </div>

        {/* Results Column (Right) */}
        <div className="bg-white/60 backdrop-blur-xl border border-white p-8 rounded-[3rem] shadow-xl shadow-indigo-50/50 flex flex-col min-h-[400px]">
          <h2 className="text-xl font-black text-[#3E3B52] mb-6">Neural Network Analysis</h2>
          
          {!file && !isScanning && !results && (
            <div className="flex-1 bg-white/40 rounded-[2rem] border-2 border-dashed border-[#A09CB0]/20 flex flex-col items-center justify-center text-center p-8">
              <BrainCircuit className="w-16 h-16 text-[#A09CB0] mb-4 opacity-50" />
              <p className="text-[#8E8AAB] font-bold">Awaiting media input...</p>
              <p className="text-[#A09CB0] text-sm mt-2 max-w-xs">Upload an image to evaluate it against our synthetic generation models.</p>
            </div>
          )}

          {isScanning && (
            <div className="flex-1 bg-white/40 rounded-[2rem] border border-white flex flex-col items-center justify-center shadow-inner p-8">
              <div className="animate-spin rounded-full h-12 w-12 border-[4px] border-[#E5E1E6] border-t-emerald-500 mb-6"></div>
              <p className="text-emerald-500 font-black text-sm uppercase tracking-widest animate-pulse">Running Tensor Analysis...</p>
              <div className="w-full max-w-xs bg-slate-100 h-2 rounded-full overflow-hidden mt-6">
                <div className="bg-emerald-400 h-full w-1/2 animate-[progress_1s_ease-in-out_infinite]"></div>
              </div>
            </div>
          )}

          {results && (
            <div className="flex-1 space-y-8 animate-in fade-in zoom-in duration-500">
              
              <div className="bg-emerald-50 border border-emerald-100 p-6 rounded-[2rem] flex items-start shadow-sm">
                <CheckCircle2 className="w-8 h-8 text-emerald-500 mr-4 flex-shrink-0" />
                <div>
                  <h3 className="text-emerald-700 font-black text-lg tracking-tight mb-1">Analysis Complete</h3>
                  <p className="text-emerald-600/80 font-medium text-sm leading-relaxed">
                    The Swin Transformer has evaluated the pixel structures and noise variance. Review the confidence scores below.
                  </p>
                </div>
              </div>

              <div className="space-y-6 bg-white/80 p-8 rounded-[2rem] border border-white shadow-sm">
                
                {/* Authentic Bar */}
                <div>
                  <div className="flex justify-between items-end mb-2">
                    <span className="text-[10px] font-black uppercase tracking-[0.2em] text-[#A09CB0]">Authentic / Camera</span>
                    <span className="text-emerald-500 font-black text-xl">{results.real}%</span>
                  </div>
                  <div className="w-full bg-[#E5E1E6] rounded-full h-3">
                    <div className="bg-emerald-500 h-3 rounded-full transition-all duration-1000 ease-out shadow-sm" style={{ width: `${results.real}%` }}></div>
                  </div>
                </div>

                {/* AI Generated Bar */}
                <div>
                  <div className="flex justify-between items-end mb-2">
                    <span className="text-[10px] font-black uppercase tracking-[0.2em] text-[#A09CB0]">AI Generated</span>
                    <span className="text-rose-500 font-black text-xl">{results.ai}%</span>
                  </div>
                  <div className="w-full bg-[#E5E1E6] rounded-full h-3">
                    <div className="bg-rose-500 h-3 rounded-full transition-all duration-1000 ease-out shadow-sm" style={{ width: `${results.ai}%` }}></div>
                  </div>
                </div>

              </div>
              
              <button 
                onClick={() => { setFile(null); setResults(null); }} 
                className="w-full py-4 bg-white border-2 border-[#E5E1E6] hover:border-[#3E3B52] text-[#3E3B52] text-xs font-black uppercase tracking-widest rounded-full transition-all shadow-sm"
              >
                Reset Analyzer
              </button>
            </div>
          )}
        </div>

      </div>
    </div>
  );
}